### ISSUE TITLE
Unexpected token

### ISSUE THREAD

**Issue by gelato** [vatesfr/xo-server#304]
I don't know where to post this issue, maybe you can help.
I have two xen orchestras - one from github and the other one a free version of appliance from xen orchestra site.
The one from github works perfectly, while the other, free one, fails to start after an update, with reason:

```
/usr/local/lib/node_modules/xo-server/bin/xo-server:11
process.on('unhandledRejection', (reason) => {
                                          ^^
SyntaxError: Unexpected token =>
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

So maybe you can help me pinpoint the source of the problem...
node -v
v0.12.4
npm -v
3.4.0

Debian GNU/Linux 7

**Comment by julien-f** [comment]
It's ES6 syntax and it requires at least Node 4 (LTS).

We try to stay as compatible as possible but sometimes new syntax makes it through :stuck_out_tongue:
