### ISSUE TITLE
smb2-promise causing crash

### ISSUE THREAD

**Issue by bcdonadio** [vatesfr/xo-server#327]
The following problem happens when running both the stable and next-release branches. It can be fixed simply by changing the version of @marsaud/smb2-promise from "^0.2.0" to "^0.1.0" in the packages.json file. However, I'm not sure about the security implications of this downgrade.

```
Starting "Xen Orchestra administration interface"...
> xo-server@4.17.0 start /opt/xo-server
> node bin/xo-server
/opt/xo-server/node_modules/@marsaud/smb2/lib/api/createWriteStream.js:1
(function (exports, require, module, __filename, __dirname) { 'use strict';var _get=require('babel-runtime/helpers/get')['default'];var _inherits=require('babel-runtime/helpers/inherits')['default'];var _createClass=require('babel-runtime/helpers/create-class')['default'];var _classCallCheck=require('babel-runtime/helpers/class-call-check')['default'];var _regeneratorRuntime=require('babel-runtime/regenerator')['default'];var _Promise=require('babel-runtime/core-js/promise')['default'];var _interopRequireDefault=require('babel-runtime/helpers/interop-require-default')['default'];Object.defineProperty(exports,'__esModule',{value:true});var marked0$0=[fibonacci].map(_regeneratorRuntime.mark);var _toolsBigint=require('../tools/bigint');var _toolsBigint2=_interopRequireDefault(_toolsBigint);var _bluebird=require('bluebird');var _bluebird2=_interopRequireDefault(_bluebird);var _toolsSmb2Forge=require('../tools/smb2-forge');var _stream=requi
TypeError: Cannot read property 'mark' of undefined
at Object.<anonymous> (/opt/xo-server/node_modules/@marsaud/smb2/lib/api/createWriteStream.js:1:631)
at require (internal/module.js:20:19)
at Object.<anonymous> (/opt/xo-server/node_modules/@marsaud/smb2/lib/smb2.js:96:57)
at require (internal/module.js:20:19)
at Object.<anonymous> (/opt/xo-server/node_modules/@marsaud/smb2-promise/index.js:1:388)
at require (internal/module.js:20:19)
at Object.<anonymous> (/source/remote-handlers/smb.js:1)
at require (internal/module.js:20:19)
at Object.<anonymous> (/source/xo-mixins/remotes.js:3)
at require (internal/module.js:20:19)
at Object.<anonymous> (/source/xo-mixins/index.js:30)
at require (internal/module.js:20:19)
at Object.<anonymous> (/source/xo.js:7)
at require (internal/module.js:20:19)
at Object.<anonymous> (/source/index.js:37)
at require (internal/module.js:20:19)
at Object.<anonymous> (/opt/xo-server/index.js:11:18)
at require (internal/module.js:20:19)
at Object.<anonymous> (/opt/xo-server/bin/xo-server:31:25)
npm ERR! Linux 3.10.0-327.13.1.el7.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v5.11.1
npm ERR! npm  v3.9.3
npm ERR! code ELIFECYCLE
npm ERR! xo-server@4.17.0 start: `node bin/xo-server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the xo-server@4.17.0 start script 'node bin/xo-server'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the xo-server package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node bin/xo-server
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs xo-server
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls xo-server
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /opt/xo-server/npm-debug.log
xo.service: main process exited, code=exited, status=1/FAILURE
Unit xo.service entered failed state.
xo.service failed.
xo.service holdoff time over, scheduling restart.
start request repeated too quickly for xo.service
Failed to start "Xen Orchestra administration interface".
Unit xo.service entered failed state.
```
The environment is the following:
### Context
xo-server: vatesfr/xo-server@e7feb99f8dab0a807af51d9360b5897a29345a49
xo-web: vatesfr/xo-web@1b2ca8e69ed82889a28b2524e6cc4195c454e4a7
```
{ 'xo-web': '4.16.1',
  npm: '3.9.3',
  ares: '1.10.1-DEV',
  http_parser: '2.5.2',
  icu: '56.1',
  modules: '46',
  node: '4.4.5',
  openssl: '1.0.2h',
  uv: '1.8.0',
  v8: '4.5.103.35',
  zlib: '1.2.8' }
```

**Comment by bcdonadio** [comment]
@marsaud You probably will want to take a look on this. If you need any further info, just ask.

**Comment by yobasystems** [comment]
+1 I'm also experiencing an issue with this

**Comment by julien-f** [comment]
The fixes are almost integrated :)

**Comment by olivierlambert** [comment]
Fixed in https://github.com/vatesfr/xo-server/commit/22ff330ee781b780f4f0ece5ac913f4eb0181349
