### ISSUE TITLE
TypeError: Cannot call method 'getObjects' of undefined

### ISSUE THREAD

**Issue by hoerup** [vatesfr/xo-server#44]
Using clean build of next-release branch I get this error from xo-server:

  xo:api xo.getAllObjects(...) +33ms
  xo:api Error: xo.getAllObjects(...) → TypeError: Cannot call method 'getObjects' of undefined +43ms
TypeError: Cannot call method 'getObjects' of undefined
    at $XO.exports.getAllObjects (/root/xo-server/src/api/xo.js:1:39)
    at Bluebird.try.then.then.result (/root/xo-server/src/api.js:176:21)
    at process._tickCallback (node.js:419:13)
From previous event:
    at Api.call (/root/xo-server/src/api.js:173:8)
    at JsonRpcServer.<anonymous> (/root/xo-server/src/index.js:182:16)
From previous event:
    at JsonRpcServer$exec (/root/xo-server/node_modules/json-rpc/index.js:264:22)
From previous event:
    at JsonRpcServer._write (/root/xo-server/node_modules/json-rpc/index.js:211:8)
    at doWrite (/root/xo-server/node_modules/json-rpc/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/root/xo-server/node_modules/json-rpc/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at JsonRpcServer.Writable.write (/root/xo-server/node_modules/json-rpc/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at WebSocket.<anonymous> (/root/xo-server/src/index.js:201:12)
    at WebSocket.emit (events.js:98:17)
    at Receiver.ontext (/root/xo-server/node_modules/ws/lib/WebSocket.js:798:10)
    at /root/xo-server/node_modules/ws/lib/Receiver.js:473:18
    at /root/xo-server/node_modules/ws/lib/Receiver.js:357:7
    at /root/xo-server/node_modules/ws/lib/PerMessageDeflate.js:217:5
    at afterWrite (_stream_writable.js:277:3)
    at onwrite (_stream_writable.js:269:7)
    at WritableState.onwrite (_stream_writable.js:96:5)
    at afterTransform (_stream_transform.js:99:5)
    at TransformState.afterTransform (_stream_transform.js:74:12)
    at Zlib.callback (zlib.js:455:5)
  xo:api acl.getCurrent(...) +5ms
  xo:api acl.getCurrent(...) → object +2ms

**Comment by olivierlambert** [comment]
Just built from scratch, can't reproduce. Can you give me your `node -v` and `npm -v` output?

**Comment by hoerup** [comment]
root@xoa-dev:~# node -v
v0.10.33
root@xoa-dev:~# npm -v
2.5.0

**Comment by olivierlambert** [comment]
Okay, almost the same (just 2.5.1 for `npm`), I did:

```
$ git clone git@github.com:vatesfr/xo-server.git
$ cd xo-server/
$ git checkout next-release
$ npm i
$ npm start
```

And it works!

**Comment by hoerup** [comment]
1) I also get this xo:xapi error during the startup (don't know if it's related):

  xo:xapi root@192.168.12.5:443: VGPU_type.get_all_records(...) +3ms
  xo:xapi Error from root@192.168.12.5:443: MESSAGE_REMOVED +2s
  xo:xo 2534 objects fetched from root@192.168.12.5 +7s
  xo:xo objects inserted into the database +3s

2) the stacktrace gets dumped during/after login to xo-web

**Comment by olivierlambert** [comment]
1/ This is perfectly fine :)

2/ Ok, so It's after `xo-server` starts. So it's triggered by a login. I'll try to reproduce the behavior. Maybe it's a good idea to clean your current redis database. We made some changes which probably trigger that.

Do a `redis-cli flush-all` and try again :)

**Comment by olivierlambert** [comment]
Gotcha!

```
  xo:api Error: xo.getAllObjects(...) → TypeError: Cannot call method 'getObjects' of undefined +10ms
TypeError: Cannot call method 'getObjects' of undefined
    at $XO.exports.getAllObjects (/home/olivier/xo-server/src/api/xo.js:1:39)
    at Bluebird.try.then.then.result (/home/olivier/xo-server/src/api.js:176:21)
    at process._tickCallback (node.js:442:13)
From previous event:
    at Api.call (/home/olivier/xo-server/src/api.js:173:8)
    at JsonRpcServer.<anonymous> (/home/olivier/xo-server/src/index.js:182:16)
From previous event:
    at JsonRpcServer$exec (/home/olivier/xo-server/node_modules/json-rpc/index.js:264:22)
From previous event:
    at JsonRpcServer._write (/home/olivier/xo-server/node_modules/json-rpc/index.js:211:8)
    at doWrite (/home/olivier/xo-server/node_modules/json-rpc/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/home/olivier/xo-server/node_modules/json-rpc/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at JsonRpcServer.Writable.write (/home/olivier/xo-server/node_modules/json-rpc/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at WebSocket.<anonymous> (/home/olivier/xo-server/src/index.js:201:12)
    at WebSocket.emit (events.js:98:17)
    at Receiver.ontext (/home/olivier/xo-server/node_modules/ws/lib/WebSocket.js:798:10)
    at /home/olivier/xo-server/node_modules/ws/lib/Receiver.js:473:18
    at /home/olivier/xo-server/node_modules/ws/lib/Receiver.js:357:7
    at /home/olivier/xo-server/node_modules/ws/lib/PerMessageDeflate.js:217:5
    at afterWrite (_stream_writable.js:278:3)
    at onwrite (_stream_writable.js:270:7)
    at WritableState.onwrite (_stream_writable.js:97:5)
    at afterTransform (_stream_transform.js:99:5)
    at TransformState.afterTransform (_stream_transform.js:74:12)
    at Zlib.callback (zlib.js:456:5)
```

**Comment by hoerup** [comment]
It works :)

**Comment by olivierlambert** [comment]
\o/
