### ISSUE TITLE
create new nfs sr error

### ISSUE THREAD

**Issue by arjing** [vatesfr/xo-server#56]
error message:
```
  xo:api Error: sr.probeNfs(...) → XapiError: SR_BACKEND_FAILURE_101 +87ms
XapiError: SR_BACKEND_FAILURE_101
    at D:\0work\xo\3.9.1\xo-server\node_modules\xen-api\src\index.js:288:4
From previous event:
    at Xapi._rawCall (D:\0work\xo\3.9.1\xo-server\node_modules\xen-api\src\index.js:278:11)
    at Xapi._transportCall (D:\0work\xo\3.9.1\xo-server\node_modules\xen-api\src\index.js:240:30)
```
code:
```
 try {
    wait(xapi.call(
      'SR.probe',
      host.ref,
      deviceConfig,
      'nfs',
      {}
    ))

    throw new Error('the call above should have thrown an error')
  } catch (error) {
    if (error[0] !== 'SR_BACKEND_FAILURE_101') {
      throw error
    }

    xml = parseXml(error[3])
  }
```

I changed the code to:
```
  try {
    wait(xapi.call(
      'SR.probe',
      host.ref,
      deviceConfig,
      'nfs',
      {}
    ))

    throw new Error('the call above should have thrown an error')
  } catch (error) {
    if (error['code'] !== 'SR_BACKEND_FAILURE_101') {
      throw error
    }

    xml = parseXml(error['params'][2])
```
then it is ok

Modify the code so that correct?

**Comment by olivierlambert** [comment]
Hi,

Thanks for your report.
Which version of XenServer do you have?

**Comment by arjing** [comment]
version ：6.2

**Comment by olivierlambert** [comment]
Okay, it's probably due to our recent changes. Will fix that today.

**Comment by olivierlambert** [comment]
Thanks for your feedback, the bug is fixed in `next-release` branch.
