### ISSUE TITLE
After tried fresh install xo-server startup error

### ISSUE THREAD

**Issue by sjkeerthi** [vatesfr/xo-server#63]
After I followed the installation instruction I don't see any error while npm install and build.
After I start the services I could see error during start up.

Error
====
✖ undefined is not a function
TypeError: undefined is not a function
    at main$ (/source/index.js:385:15)
    at tryCatch (/opt/xo-server/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/opt/xo-server/node_modules/babel-runtime/regenerator/runtime.js:231:22)
    at GeneratorFunctionPrototype.Gp.(anonymous function) [as next] (/opt/xo-server/node_modules/babel-runtime/regenerator/runtime.js:264:19)
    at tryCatch (/opt/xo-server/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.step (/opt/xo-server/node_modules/babel-runtime/regenerator/runtime.js:116:22)
    at /opt/xo-server/node_modules/babel-runtime/regenerator/runtime.js:130:7
    at Promise.exp (/opt/xo-server/node_modules/babel-runtime/node_modules/core-js/library/modules/$.def.js:38:36)
    at Object.runtime.async (/opt/xo-server/node_modules/babel-runtime/regenerator/runtime.js:110:12)
    at main (/source/index.js:453:23)
From previous event:
    at execPromise (/opt/xo-server/node_modules/exec-promise/index.js:59:22)
    at Object.<anonymous> (/opt/xo-server/bin/xo-server:7:24)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

**Comment by sjkeerthi** [comment]
debug log

0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'start' ]
2 info using npm@2.11.1
3 info using node@v0.12.4
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart xo-server@4.0.2
6 info start xo-server@4.0.2
7 verbose unsafe-perm in lifecycle true
8 info xo-server@4.0.2 Failed to exec start script
9 verbose stack Error: xo-server@4.0.2 start: `node bin/xo-server`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
9 verbose stack     at EventEmitter.emit (events.js:110:17)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at ChildProcess.emit (events.js:110:17)
9 verbose stack     at maybeClose (child_process.js:1015:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
10 verbose pkgid xo-server@4.0.2
11 verbose cwd /opt/xo-server
12 error Linux 2.6.32-504.16.2.el6.x86_64
13 error argv "node" "/usr/local/bin/npm" "start"
14 error node v0.12.4
15 error npm  v2.11.1
16 error code ELIFECYCLE
17 error xo-server@4.0.2 start: `node bin/xo-server`
17 error Exit status 1
18 error Failed at the xo-server@4.0.2 start script 'node bin/xo-server'.
18 error This is most likely a problem with the xo-server package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     node bin/xo-server
18 error You can get their info via:
18 error     npm owner ls xo-server
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by julien-f** [comment]
Cannot reproduce, which git branch are you using?

**Comment by sjkeerthi** [comment]
xo-server v4.0.2

**Comment by sjkeerthi** [comment]
I just did the 

git clone https://github.com/vatesfr/xo-server

**Comment by julien-f** [comment]
So the `master` branch, that's weird, I don't have any issues…

@olivierlambert any issues on your side?

**Comment by sjkeerthi** [comment]
Do I need to check any version of rpms because I just did the latest update of nodejs.

nodesource-release-el6-1.noarch
nodejs-0.10.38-1nodesource.el6.x86_64

Is this because of that

**Comment by julien-f** [comment]
If you update Node, you must rebuild all previously installed dependencies with `npm rebuild`.

I am currently using Node 0.12, will try with 0.10.

**Comment by sjkeerthi** [comment]
issue been resolved by removing the two rpm and did the npm rebuild. It worked :-)

**Comment by julien-f** [comment]
Great :)
