### ISSUE TITLE
xo-server is broken with the bundled alpha package

### ISSUE THREAD

**Issue by olivierlambert** [vatesfr/xo-server#64]
Install is fine (online of offline):

```
# npm i -g xo-server-4.0.3-alpha.2.tgz 
/usr/local/bin/xo-server -> /usr/local/lib/node_modules/xo-server/bin/xo-server
npm WARN unmet dependency /usr/local/lib/node_modules/xo-server/node_modules/xen-api requires source-map-support@'^0.2.10' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/xo-server/node_modules/source-map-support,
npm WARN unmet dependency which is version 0.3.1
xo-server@4.0.3-alpha.2 /usr/local/lib/node_modules/xo-server
```

But when I run the program:

```
# xo-server  

/usr/local/lib/node_modules/xo-server/node_modules/hashy/node_modules/bcrypt/node_modules/bindings/bindings.js:88
  err = new Error('Could not locate the bindings file. Tried:\n'
        ^
Error: Could not locate the bindings file. Tried:
 → /usr/local/lib/node_modules/xo-server/node_modules/hashy/node_modules/bcrypt/build/bcrypt_lib.node
 → /usr/local/lib/node_modules/xo-server/node_modules/hashy/node_modules/bcrypt/build/Debug/bcrypt_lib.node
 → /usr/local/lib/node_modules/xo-server/node_modules/hashy/node_modules/bcrypt/build/Release/bcrypt_lib.node
 → /usr/local/lib/node_modules/xo-server/node_modules/hashy/node_modules/bcrypt/out/Debug/bcrypt_lib.node
 → /usr/local/lib/node_modules/xo-server/node_modules/hashy/node_modules/bcrypt/Debug/bcrypt_lib.node
 → /usr/local/lib/node_modules/xo-server/node_modules/hashy/node_modules/bcrypt/out/Release/bcrypt_lib.node
 → /usr/local/lib/node_modules/xo-server/node_modules/hashy/node_modules/bcrypt/Release/bcrypt_lib.node
 → /usr/local/lib/node_modules/xo-server/node_modules/hashy/node_modules/bcrypt/build/default/bcrypt_lib.node
 → /usr/local/lib/node_modules/xo-server/node_modules/hashy/node_modules/bcrypt/compiled/0.12.4/linux/x64/bcrypt_lib.node
    at bindings (/usr/local/lib/node_modules/xo-server/node_modules/hashy/node_modules/bcrypt/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/usr/local/lib/node_modules/xo-server/node_modules/hashy/node_modules/bcrypt/bcrypt.js:3:35)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/xo-server/node_modules/hashy/index.js:12:36)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/source/models/user.js:4:24)
```

**Comment by julien-f** [comment]
I think this has been fixed, @olivierlambert?

**Comment by olivierlambert** [comment]
I think it is, or if it wasn't the case, XOA would be broken
