### ISSUE TITLE
After Upgrade to 4.2: Unhandled rejection Error: Unknown XML-RPC tag 'H1'

### ISSUE THREAD

**Issue by UA2** [vatesfr/xo-server#74]
After upgrading to 4.2, I get for one of my pools this message and all objects from this pools are missing.

The pool is at 6.2SP1 (016).

Following is the traceback:

Unhandled rejection Error: Unknown XML-RPC tag 'H1'
    at [object Object].Deserializer.onError (/srv/xoa/xo-server/node_modules/xen-api/node_modules/xmlrpc/lib/deserializer.js:109:20)
    at [object Object].Deserializer.onClosetag (/srv/xoa/xo-server/node_modules/xen-api/node_modules/xmlrpc/lib/deserializer.js:202:14)
    at Object.me._parser.(anonymous function) [as onclosetag] (/srv/xoa/xo-server/node_modules/xen-api/node_modules/xmlrpc/node_modules/sax/lib/sax.js:245:15)
    at emit (/srv/xoa/xo-server/node_modules/xen-api/node_modules/xmlrpc/node_modules/sax/lib/sax.js:615:33)
    at emitNode (/srv/xoa/xo-server/node_modules/xen-api/node_modules/xmlrpc/node_modules/sax/lib/sax.js:620:3)
    at closeTag (/srv/xoa/xo-server/node_modules/xen-api/node_modules/xmlrpc/node_modules/sax/lib/sax.js:861:5)
    at Object.write (/srv/xoa/xo-server/node_modules/xen-api/node_modules/xmlrpc/node_modules/sax/lib/sax.js:1294:29)
    at SAXStream.write (/srv/xoa/xo-server/node_modules/xen-api/node_modules/xmlrpc/node_modules/sax/lib/sax.js:227:16)
    at Client.<anonymous> (/srv/xoa/xo-server/node_modules/xen-api/node_modules/xmlrpc/lib/client.js:109:14)
    at Client.methodCall (/srv/xoa/xo-server/node_modules/xen-api/node_modules/xmlrpc/lib/client.js:106:27)
    at Client.tryCatcher (/srv/xoa/xo-server/node_modules/bluebird/js/main/util.js:24:31)
    at Xapi._rawCall (/srv/xoa/xo-server/node_modules/xen-api/src/index.js:382:17)
    at Xapi._transportCall (/srv/xoa/xo-server/node_modules/xen-api/src/index.js:350:17)
    at Async._schedule (/srv/xoa/xo-server/node_modules/bluebird/js/main/schedule.js:11:53)
    at Async._queueTick (/srv/xoa/xo-server/node_modules/bluebird/js/main/async.js:200:14)
    at AsyncSettlePromises [as settlePromises] (/srv/xoa/xo-server/node_modules/bluebird/js/main/async.js:127:10)

**Comment by julien-f** [comment]
It looks like it did get a valid XML-RPC response, are you sure about the server's address?

**Comment by UA2** [comment]
After a restart toolstack it works again, should have taken this into account before writing.

Thanks!
