### ISSUE TITLE
Can't login, "Error: Unknown authentication strategy "signin"

### ISSUE THREAD

**Issue by AlexanderLJ** [vatesfr/xo-server#84]
This error happens on both the manual setup and when using the xva. When I try to login, even if the username or password is wrong, it will give me this error no matter what. 

    Error: Unknown authentication strategy "signin"
    at attempt (/home/xoauser/xo-server/node_modules/passport/lib/middleware/authenticate.js:166:37)
    at authenticate (/home/xoauser/xo-server/node_modules/passport/lib/middleware/authenticate.js:342:7)
    at callee$1$0$ (/source/index.js:171:9)
    at tryCatch (/home/xoauser/xo-server/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/home/xoauser/xo-server/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/home/xoauser/xo-server/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at invoke (/home/xoauser/xo-server/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at enqueueResult (/home/xoauser/xo-server/node_modules/babel-runtime/regenerator/runtime.js:185:17)
    at new Promise (/home/xoauser/xo-server/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:178:7)
    at AsyncIterator.enqueue (/home/xoauser/xo-server/node_modules/babel-runtime/regenerator/runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (/home/xoauser/xo-server/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at Object.runtime.async (/home/xoauser/xo-server/node_modules/babel-runtime/regenerator/runtime.js:209:12)
    at callee$1$0 (/source/index.js:174:16)
    at Layer.handle [as handle_request] (/home/xoauser/xo-server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/xoauser/xo-server/node_modules/express/lib/router/index.js:312:13)
    at /home/xoauser/xo-server/node_modules/express/lib/router/index.js:280:7

**Comment by olivierlambert** [comment]
Hi,

I need to know more: are you using XOA or the manual installation from the source? Is it from a fresh install or a update?

**Comment by AlexanderLJ** [comment]
Sorry my bad, I must have somehow submitted this post without knowing because I was still writing my summary! My apologies, the title was suppose to be "Can't login, "Error: Unknown authentication strategy "signin"" as well. 

This error happens on both the manual setup and when using the xva. When I try to login, even if the username or password is wrong, it will give me this error no matter what. 

    Error: Unknown authentication strategy "signin"
    at attempt (/home/xoauser/xo-server/node_modules/passport/lib/middleware/authenticate.js:166:37)
    at authenticate (/home/xoauser/xo-server/node_modules/passport/lib/middleware/authenticate.js:342:7)
    at callee$1$0$ (/source/index.js:171:9)
    at tryCatch (/home/xoauser/xo-server/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/home/xoauser/xo-server/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/home/xoauser/xo-server/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at invoke (/home/xoauser/xo-server/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at enqueueResult (/home/xoauser/xo-server/node_modules/babel-runtime/regenerator/runtime.js:185:17)
    at new Promise (/home/xoauser/xo-server/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:178:7)
    at AsyncIterator.enqueue (/home/xoauser/xo-server/node_modules/babel-runtime/regenerator/runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (/home/xoauser/xo-server/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at Object.runtime.async (/home/xoauser/xo-server/node_modules/babel-runtime/regenerator/runtime.js:209:12)
    at callee$1$0 (/source/index.js:174:16)
    at Layer.handle [as handle_request] (/home/xoauser/xo-server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/xoauser/xo-server/node_modules/express/lib/router/index.js:312:13)
    at /home/xoauser/xo-server/node_modules/express/lib/router/index.js:280:7

**Comment by olivierlambert** [comment]
You probably have an old cookie. Be sure to refresh your browser or try in private mode.

**Comment by AlexanderLJ** [comment]
Problem doesn't seem to solved by clearing cookies,  It fails on both Firefox and Chrome. My first attempt was using the xva and Firefox, but it just gave me that error. This is my first time using Xen Orchestra.

**Comment by olivierlambert** [comment]
Do you have the same output in the log of XOA (the xva)? The logfile is in `/var/log/syslog`

It's easier to understand the problem with XOA because we know about the system (contrary to the manual install)

**Comment by AlexanderLJ** [comment]
I imported the xva again and the same error seems to show up in `/var/log/syslog`. (The log files are massive by the way, around 18MB.)

>root@xoa:~# tail /var/log/syslog
>Sep 11 22:13:27 xoa xo-server[1194]: at invoke (/usr/local/lib/node_modules/xo-server/node_modules/babel-runtime/regenerator/runtime.js:136:37)
>Sep 11 22:13:27 xoa xo-server[1194]: at enqueueResult (/usr/local/lib/node_modules/xo-server/node_modules/babel-runtime/regenerator/runtime.js:185:17)
>Sep 11 22:13:27 xoa xo-server[1194]: at new Promise (/usr/local/lib/node_modules/xo-server/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:181:7)
>Sep 11 22:13:27 xoa xo-server[1194]: at AsyncIterator.enqueue (/usr/local/lib/node_modules/xo-server/node_modules/babel-runtime/regenerator/runtime.js:184:12)
>Sep 11 22:13:27 xoa xo-server[1194]: at AsyncIterator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/xo-server/node_modules/babel-runtime/regenerator/runtime.js:100:21)
>Sep 11 22:13:27 xoa xo-server[1194]: at Object.runtime.async (/usr/local/lib/node_modules/xo-server/node_modules/babel-runtime/regenerator/runtime.js:209:12)
>Sep 11 22:13:27 xoa xo-server[1194]: at callee$1$0 (/source/index.js:174:16)
>Sep 11 22:13:27 xoa xo-server[1194]: at Layer.handle [as handle_request] (/usr/local/lib/node_modules/xo-server/node_modules/express/lib/router/layer.js:95:5)
>Sep 11 22:13:27 xoa xo-server[1194]: at trim_prefix (/usr/local/lib/node_modules/xo-server/node_modules/express/lib/router/index.js:312:13)
>Sep 11 22:13:27 xoa xo-server[1194]: at /usr/local/lib/node_modules/xo-server/node_modules/express/lib/router/index.js:280:7>

**Comment by olivierlambert** [comment]
Do you have some text before the first line? I would like to see if I miss something. Thanks!

Did you modify the config or it's out of the box?

**Comment by AlexanderLJ** [comment]
This is straight out of the box, imported into Xen and started up, here's some more of the log.

>Sep 11 22:13:19 xoa xoa-updater[1193]: Server listening on 9001
>Sep 11 22:13:20 xoa xo-server[1194]: Fri, 11 Sep 2015 20:13:20 GMT app-conf /etc/xo-server/config.yaml
>Sep 11 22:13:20 xoa xo-server[1194]: Fri, 11 Sep 2015 20:13:20 GMT xo:main Configuration loaded.
>Sep 11 22:13:20 xoa xo-server[1194]: Fri, 11 Sep 2015 20:13:20 GMT xo:main Web server listening on http://[::]:80
>Sep 11 22:13:21 xoa xo-server[1194]: Fri, 11 Sep 2015 20:13:21 GMT xo:perf blocked for 52ms
>Sep 11 22:13:21 xoa xo-server[1194]: Fri, 11 Sep 2015 20:13:21 GMT xo:main Web server listening on https://[::]:443
>Sep 11 22:13:21 xoa xo-server[1194]: Fri, 11 Sep 2015 20:13:21 GMT xo:perf blocked for 91ms
>Sep 11 22:13:21 xoa xo-server[1194]: Fri, 11 Sep 2015 20:13:21 GMT xo:main Setting up / → /usr/local/lib/node_modules/xo-web/dist
>Sep 11 22:13:21 xoa xo-server[1194]: Fri, 11 Sep 2015 20:13:21 GMT xo:perf blocked for 98ms
>Sep 11 22:13:27 xoa xo-server[1194]: Fri, 11 Sep 2015 20:13:27 GMT xo:perf blocked for 75ms
>Sep 11 22:13:27 xoa xo-server[1194]: Error: Unknown authentication strategy "signin"
>Sep 11 22:13:27 xoa xo-server[1194]: at attempt (/usr/local/lib/node_modules/xo-server/node_modules/passport/lib/middleware/authenticate.js:166:37)
>Sep 11 22:13:27 xoa xo-server[1194]: at authenticate (/usr/local/lib/node_modules/xo-server/node_modules/passport/lib/middleware/authenticate.js:342:7)
>Sep 11 22:13:27 xoa xo-server[1194]: at callee$1$0$ (/source/index.js:171:9)
>Sep 11 22:13:27 xoa xo-server[1194]: at tryCatch (/usr/local/lib/node_modules/xo-server/node_modules/babel-runtime/regenerator/runtime.js:67:40)
>Sep 11 22:13:27 xoa xo-server[1194]: at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/xo-server/node_modules/babel-runtime/regenerator/runtime.js:315:22)
>Sep 11 22:13:27 xoa xo-server[1194]: at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/xo-server/node_modules/babel-runtime/regenerator/runtime.js:100:21)
>Sep 11 22:13:27 xoa xo-server[1194]: at invoke (/usr/local/lib/node_modules/xo-server/node_modules/babel-runtime/regenerator/runtime.js:136:37)
>Sep 11 22:13:27 xoa xo-server[1194]: at enqueueResult (/usr/local/lib/node_modules/xo-server/node_modules/babel-runtime/regenerator/runtime.js:185:17)
>Sep 11 22:13:27 xoa xo-server[1194]: at new Promise (/usr/local/lib/node_modules/xo-server/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:181:7)
>Sep 11 22:13:27 xoa xo-server[1194]: at AsyncIterator.enqueue (/usr/local/lib/node_modules/xo-server/node_modules/babel-runtime/regenerator/runtime.js:184:12)
>Sep 11 22:13:27 xoa xo-server[1194]: at AsyncIterator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/xo-server/node_modules/babel-runtime/regenerator/runtime.js:100:21)
>Sep 11 22:13:27 xoa xo-server[1194]: at Object.runtime.async (/usr/local/lib/node_modules/xo-server/node_modules/babel-runtime/regenerator/runtime.js:209:12)
>Sep 11 22:13:27 xoa xo-server[1194]: at callee$1$0 (/source/index.js:174:16)
>Sep 11 22:13:27 xoa xo-server[1194]: at Layer.handle [as handle_request] (/usr/local/lib/node_modules/xo-server/node_modules/express/lib/router/layer.js:95:5)
>Sep 11 22:13:27 xoa xo-server[1194]: at trim_prefix (/usr/local/lib/node_modules/xo-server/node_modules/express/lib/router/index.js:312:13)
>Sep 11 22:13:27 xoa xo-server[1194]: at /usr/local/lib/node_modules/xo-server/node_modules/express/lib/router/index.js:280:7
>Sep 11 22:17:01 xoa /USR/SBIN/CRON[1465]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)

**Comment by olivierlambert** [comment]
Just imported the xva in my own XenServer at home, I can reproduce your problem :/

Can you check if your MD5SUM on the file is the same as mine?

```
$ md5sum xoa_free_4.5.xva 
a479699bb5152352749bd9edb51c8539  xoa_free_4.5.xva
```

**Comment by AlexanderLJ** [comment]
That's interesting... checksum is the same too.

>[root@klarence ~]# md5sum xoa_free_4.5.xva
>a479699bb5152352749bd9edb51c8539  xoa_free_4.5.xva

**Comment by olivierlambert** [comment]
oO

Interesting as you said. Any chance to have an access to your freshly imported XOA to take a look?

**Comment by AlexanderLJ** [comment]
Sure I can give you ssh access, do you have a way for me to give you the details? e.g IRC or mail.

**Comment by olivierlambert** [comment]
I'm on IRC right now, #xen-orchestra channel on freenode. Let's start there.

**Comment by olivierlambert** [comment]
@AlexanderLJ seems to be redirected to `signin/signin` in the URL. From my side, I don't have the problem, even by accessing the XOA from outside :/

Any idea @julien-f ?

**Comment by AlexanderLJ** [comment]
Screenshot of the error, http://i.imgur.com/7V3xkcU.png

**Comment by olivierlambert** [comment]
It was a wrong user `admin@admin.com` instead of `admin@admin.net`. We'll fix this obscure message soon.
