### ISSUE TITLE
Error While install 4.5

### ISSUE THREAD

**Issue by sjkeerthi** [vatesfr/xo-server#86]
Hi 

Error while installing xo-server & xo-web during npm install 4.5 on with below environment.
not sure can we ignore this erros and to proceed further.

CentOS 6.6 
node : 0.12.7
npm  : 2.11.3

xo-server Error
===============

```
npm WARN peerDependencies The peer dependency eslint@>=0.24.1 included from eslint-config-standard-react will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN optional dep failed, continuing fsevents@0.3.8
npm WARN peerDependencies The peer dependency eslint@^1.0.0 included from eslint-config-standard will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency eslint@^1.0.0 included from eslint-plugin-standard will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
 
> bcrypt@0.8.5 install /opt/xo-server/node_modules/hashy/node_modules/bcrypt
> node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: 404 response dowloading http://nodejs.org/dist/v0.12.7/node-v0.12.7.tar.gz
gyp ERR! stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:251:14)
gyp ERR! stack     at Request.emit (events.js:129:20)
gyp ERR! stack     at Request.onRequestResponse (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1142:10)
gyp ERR! stack     at ClientRequest.emit (events.js:107:17)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:426:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:111:23)
gyp ERR! stack     at Socket.socketOnData (_http_client.js:317:20)
gyp ERR! stack     at Socket.emit (events.js:107:17)
gyp ERR! stack     at readableAddChunk (_stream_readable.js:163:16)
gyp ERR! stack     at Socket.Readable.push (_stream_readable.js:126:10)
gyp ERR! System Linux 2.6.32-573.3.1.el6.x86_64
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /opt/xo-server/node_modules/hashy/node_modules/bcrypt
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 
 
> bufferutil@1.2.1 install /opt/xo-server/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: 404 response dowloading http://nodejs.org/dist/v0.12.7/node-v0.12.7.tar.gz
gyp ERR! stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:251:14)
gyp ERR! stack     at Request.emit (events.js:129:20)
gyp ERR! stack     at Request.onRequestResponse (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1142:10)
gyp ERR! stack     at ClientRequest.emit (events.js:107:17)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:426:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:111:23)
gyp ERR! stack     at Socket.socketOnData (_http_client.js:317:20)
gyp ERR! stack     at Socket.emit (events.js:107:17)
gyp ERR! stack     at readableAddChunk (_stream_readable.js:163:16)
gyp ERR! stack     at Socket.Readable.push (_stream_readable.js:126:10)
gyp ERR! System Linux 2.6.32-573.3.1.el6.x86_64
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /opt/xo-server/node_modules/ws/node_modules/bufferutil
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
 ERR! not ok 
npm WARN optional dep failed, continuing bcrypt@0.8.5
 
> utf-8-validate@1.2.1 install /opt/xo-server/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: 404 response dowloading http://nodejs.org/dist/v0.12.7/node-v0.12.7.tar.gz
gyp ERR! stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:251:14)
gyp ERR! stack     at Request.emit (events.js:129:20)
gyp ERR! stack     at Request.onRequestResponse (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1142:10)
gyp ERR! stack     at ClientRequest.emit (events.js:107:17)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:426:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:111:23)
gyp ERR! stack     at Socket.socketOnData (_http_client.js:317:20)
gyp ERR! stack     at Socket.emit (events.js:107:17)
gyp ERR! stack     at readableAddChunk (_stream_readable.js:163:16)
gyp ERR! stack     at Socket.Readable.push (_stream_readable.js:126:10)
gyp ERR! System Linux 2.6.32-573.3.1.el6.x86_64
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /opt/xo-server/node_modules/ws/node_modules/utf-8-validate
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 
npm WARN optional dep failed, continuing bufferutil@1.2.1
npm WARN optional dep failed, continuing utf-8-validate@1.2.1
 
> v8-profiler@5.3.0 preinstall /opt/xo-server/node_modules/node-inspector/node_modules/v8-profiler
>  

 
> v8-debug@0.5.3 preinstall /opt/xo-server/node_modules/node-inspector/node_modules/v8-debug
>  

npm WARN optional dep failed, continuing default-browser-id@1.0.2
npm WARN engine xmlbuilder@2.2.1: wanted: {"node":"0.8.x || 0.10.x"} (current: {"node":"0.12.7","npm":"2.11.3"})
|
> v8-debug@0.5.3 install /opt/xo-server/node_modules/node-inspector/node_modules/v8-debug
> node-pre-gyp install --fallback-to-build

[v8-debug] Success: "/opt/xo-server/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.5.3/node-v14-linux-x64/debug.node" is installed via remote

> v8-profiler@5.3.0 install /opt/xo-server/node_modules/node-inspector/node_modules/v8-profiler
> node-pre-gyp install --fallback-to-build

[v8-profiler] Success: "/opt/xo-server/node_modules/node-inspector/node_modules/v8-profiler/build/profiler/v5.3.0/node-v14-linux-x64/profiler.node" is installed via remote
npm WARN prefer global node-inspector@0.12.3 should be installed with -g
npm WARN cannot run in wd xo-server@4.5.0 npm run build (wd=/opt/xo-server)
```

xo-web ERROR
=============

```
xo-web]# npm install
npm WARN optional dep failed, continuing fsevents@0.3.8
npm WARN peerDependencies The peer dependency eslint@>=0.24.1 included from eslint-config-standard-react will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency eslint@^1.0.0 included from eslint-config-standard will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency eslint@^1.0.0 included from eslint-plugin-standard will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN optional dep failed, continuing fsevents@0.3.8
 
> utf-8-validate@1.1.0 install /opt/xo-server/xo-web/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: 404 response dowloading http://nodejs.org/dist/v0.12.7/node-v0.12.7.tar.gz
gyp ERR! stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:251:14)
gyp ERR! stack     at Request.emit (events.js:129:20)
gyp ERR! stack     at Request.onRequestResponse (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1142:10)
gyp ERR! stack     at ClientRequest.emit (events.js:107:17)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:426:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:111:23)
gyp ERR! stack     at Socket.socketOnData (_http_client.js:317:20)
gyp ERR! stack     at Socket.emit (events.js:107:17)
gyp ERR! stack     at readableAddChunk (_stream_readable.js:163:16)
gyp ERR! stack     at Socket.Readable.push (_stream_readable.js:126:10)
gyp ERR! System Linux 2.6.32-573.3.1.el6.x86_64
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /opt/xo-server/xo-web/node_modules/ws/node_modules/utf-8-validate
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 
 
> bufferutil@1.1.0 install /opt/xo-server/xo-web/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: 404 response dowloading http://nodejs.org/dist/v0.12.7/node-v0.12.7.tar.gz
gyp ERR! stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:251:14)
gyp ERR! stack     at Request.emit (events.js:129:20)
gyp ERR! stack     at Request.onRequestResponse (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1142:10)
gyp ERR! stack     at ClientRequest.emit (events.js:107:17)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:426:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:111:23)
gyp ERR! stack     at Socket.socketOnData (_http_client.js:317:20)
gyp ERR! stack     at Socket.emit (events.js:107:17)
gyp ERR! stack     at readableAddChunk (_stream_readable.js:163:16)
gyp ERR! stack     at Socket.Readable.push (_stream_readable.js:126:10)
gyp ERR! System Linux 2.6.32-573.3.1.el6.x86_64
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /opt/xo-server/xo-web/node_modules/ws/node_modules/bufferutil
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 
npm WARN optional dep failed, continuing utf-8-validate@1.1.0
npm WARN optional dep failed, continuing bufferutil@1.1.0
```

**Comment by olivierlambert** [comment]
See https://github.com/vatesfr/xo/blob/master/doc/installation/manual_installation.md#troubleshooting
